### PR TITLE
update welcome.py

### PR DESCRIPTION
**Pull request by Utarbai**
Add new language 'ba'

### CODE REVIEW

**Comment by magul** [comment]
Hi @Utarbai, You have created pull reqeust only to semi-official mirror of pywikibot. If You want to merge your change, see: Developing pywikibot on https://www.mediawiki.org/wiki/Manual:Pywikibot

**Comment by MarcoAurelioWM** [comment]
Yes, as @magul said, this should go to Wikimedia Gerrit repo so it gets merged there. GitHub is just a mirror for the code hosted there :)

**Comment by framawiki** [comment]
Was added in https://gerrit.wikimedia.org/r/#/c/366246/. Please close this PR

**Comment by dvorapa** [comment]
Closed per @magul's and @framawiki's comment

**Pull request closed without merging**
